spring:
  application:
    name: api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        temp:
          use_jdbc_metadata_defaults: false

logging:
  level:
    org.springframework: info
    ru.sberx: info
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %X{requestId} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

application:
  unicorn:
    url: http://demosrv.unicorn.ru:81/SaleService.svc/json/
    login: WarpApi
    password: IS41NlJaUVg0
  jdbc: true